### ISSUE TITLE
Exec format error after latest update (RPi 4B)

### ISSUE THREAD

**Issue by yllekz** [linuxserver/docker-domoticz#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I'm using the "latest" tag of domoticz and have for a while now. After the latest update, the container won't start, reading "exec format error"

------------------------------

## Expected Behavior
Container should work

## Current Behavior
`s6-applyuidgid: fatal: unable to exec /usr/bin/domoticz: Exec format error`

## Steps to Reproduce

1. Pull linuxserver/domoticz:latest
2. Run container, note it won't start
3. View logs

## Environment
**OS:** Raspberry Pi OS x86
**CPU architecture:** x86_64/arm32/arm64 armhf (RPi 4B)
**How docker service was installed:** OpenMediaVault

```
---
version: "2"
services:
  domoticz:
    image: linuxserver/domoticz:latest
    container_name: domoticz
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /path/to/my/config/domoticz:/config
    ports:
      - 8082:8080 #WebUI
      - 6144:6144 #Domoticz comm port
      - 1443:1443 #Domoticz comm port
    restart: unless-stopped
```

## Docker logs

`s6-applyuidgid: fatal: unable to exec /usr/bin/domoticz: Exec format error`
