### ISSUE TITLE
Docker latest image for arm64 are still use Domoticz older source code (from 17-apr)

### ISSUE THREAD

**Issue by pgolawsk** [linuxserver/docker-domoticz#98]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Using ```docker-compose pull``` I do refresh domoticz image to the latest version of source code, which suppose to be from 28-nov.
My docker-compose image:
```image: ghcr.io/linuxserver/domoticz:latest```
which as of now refers to:
```image: ghcr.io/linuxserver/domoticz:2021.1.20211128```

## Current Behavior
Docker image image gets refreshed properly, but aparently I see in logs that the version of source code is from 17-apr, as per container logs:
```
...
2021-12-05 16:39:55.181  Status: Domoticz V2021.1 (c)2012-2021 GizMoCuz
2021-12-05 16:39:55.181  Status: Build Hash: 8547c5b7e, Date: 2021-04-17 17:29:11
...
```
I found it because this version have a bug [(4784)](https://github.com/domoticz/domoticz/issues/4784) with Satel Integra plugin which was fixed 26-apr.
First I thought this is Domoticz bug itself, but after investigation of the issue lloks linuxserver.io image is not using the latest source code.

## Steps to Reproduce

1. ```docker-compose pull```
2. ```docker-compose up -d```
3. Checking the container logs through  Poitainer I see container crashes every minute or so, due to the bug [4784](https://github.com/domoticz/domoticz/issues/4784).
4. Futher checking the log I see that source code build date is 2021-04-17 as per log above.

## Environment
**OS:** Raspbery Pi 4B, Ubuntu 21.10
**CPU architecture:** arm64
**How docker service was installed:** from oryginal repo

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml section
```
  domoticz:
    image: ghcr.io/linuxserver/domoticz:latest
    container_name: domoticz
    privileged: true
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Warsaw
    volumes:
      - ./vols/domoticz/config:/config
    ports:
      - 8080:8080
      - 6144:6144
      - 1443:1443
    restart: unless-stopped
```
